# Generated by Django 6.0.5 on 2026-07-06 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_agendamento_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assinatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='DescontoServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentual_desconto', models.DecimalField(decimal_places=2, max_digits=5)),
                ('assinatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.assinatura')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.servico')),
            ],
        ),
        migrations.AddField(
            model_name='assinatura',
            name='servicos_produtos_com_desconto',
            field=models.ManyToManyField(related_name='assinaturas_com_desconto', through='app.DescontoServico', to='app.servico'),
        ),
        migrations.CreateModel(
            name='ServicoGratis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assinatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.assinatura')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.servico')),
            ],
        ),
        migrations.AddField(
            model_name='assinatura',
            name='servicos_produtos_gratis',
            field=models.ManyToManyField(related_name='assinaturas_gratis', through='app.ServicoGratis', to='app.servico'),
        ),
    ]
